@startuml
actor "Người dùng" as User
participant "Client" as UI
participant "ProgressController" as controller
participant "ProgressService" as service
participant "UserLessonProgressRepo" as repo
participant "GamificationRepo" as gamificationRepo
database "Database (MySQL)" as DB

User -> UI: patchSegmentProgress(lessonId, payload)
activate UI

UI -> controller: updateSegmentProgress(lessonId, payload)
activate controller

controller -> service: updateSegmentProgress(lessonId, segmentId, payload)
activate service

service -> service: calculateDictationAccuracy(segmentId,\npayload.attemptCount, payload.hintUsedCount)
activate service
deactivate service

service -> repo: updateSegmentProgress(lessonId, segmentId,\nprogressPct, lastStartMs, status)
activate repo

repo -> DB : updateSegmentProgress(lessonId, segmentId,\nprogressPct, lastStartMs, status)
activate DB

DB --> repo: result
deactivate DB

repo --> service: result

opt Điểm đánh giá vượt ngưỡng đạt
    service -> gamificationRepo: updateUserGamification(user.id, xp)
    activate gamificationRepo

    gamificationRepo -> DB: updateUserGamification(user.id, xp)
    activate DB

    DB --> gamificationRepo: result
    deactivate DB

    gamificationRepo --> service: result
    deactivate gamificationRepo
end

service --> controller: result
controller --> UI: apiResponse
UI --> User: Hiển thị điểm số

loop Còn phân đoạn tiếp theo
service -> repo: getNextSegment(lessonId, segmentId)
repo -> DB: getNextSegment(lessonId, segmentId)
activate DB

DB --> repo: result
deactivate DB

repo --> service: result
service --> controller: result
controller --> UI: apiResponse
UI --> User: Hiển thị phân đoạn tiếp theo

User --> UI: Tiếp tục học
UI --> controller: Tiếp tục đánh giá\nvà hiện phân đoạn tiếp theo
else Học hết phân đoạn
controller -> service: completeLesson(userId, lessonId)
service -> repo: completeLesson(userId, lessonId, status)
repo -> DB: updateLesson(userId, lessonId, status)
activate DB

DB --> repo: result
deactivate DB

repo --> service: result
deactivate repo

service --> controller: result
deactivate service

controller --> UI: apiResponse
deactivate controller

UI --> User: Thông báo hoàn thành bài học
deactivate UI
end
@enduml