@startuml Reset_Password_Sequence
skinparam sequenceArrowThickness 1.5
skinparam roundcorner 8
skinparam responseMessageBelowArrow true
skinparam sequenceGroupBorderThickness 1.5

skinparam participant {
    BackgroundColor #EEF4FF
    BorderColor #4A7CFF
    FontStyle Bold
}
skinparam actor {
    BackgroundColor #FEFEFE
    BorderColor #333333
}
skinparam sequence {
    LifeLineBorderColor  #888888
    GroupBorderColor     #888888
    GroupBodyBackgroundColor #FAFAFA
    DividerBackgroundColor   #E8E8E8
}
actor "Khách vãng lai" as User
participant "Client" as client
participant "AuthController" as controller
participant "AuthService" as service
participant "EmailService" as mailService
participant "UserRepo" as repo
participant "RedisService" as redis
database "Database" as DB

User -> client : sendResetPasswordOTP(request)
activate client
alt Email sai định dạng
    client --> User : Thông báo lỗi:\n"Email sai định dạng"
else Email đúng định dạng
    client -> controller : sendResetPasswordOTP(request)
    activate controller

    controller   -> service : sendResetPasswordOTP(email)
    activate service

    service  -> repo  : findByEmail(email)
    activate repo

    repo  -> DB  : findByEmail(email)
    activate DB

    DB   --> repo : user
    deactivate DB

    repo   --> service : user
    deactivate repo

    alt user = null
        service  --> controller : EmailNotExistedError
        controller  --> client : responseEntity
        client --> User : Thông báo lỗi:\n"Email chưa được đăng ký"

    else user != null
        service  -> service  : otp = generateOTP()
        activate service
        deactivate service

        service  -> redis   : save(email, otp, timeoutInSeconds)
        activate redis
        redis --> service : result
        deactivate redis

        service ->> mailService: sendEmail(email, username,\notpEmailTemplate, otp, subject)
        activate mailService
        mailService -->> User: Gửi email chứa mã OTP
        deactivate mailService

        service  --> controller  : result
        deactivate service

        controller  --> client  : responseEntity
        deactivate controller

        client  --> User : Thông báo thành công,\nChuyển sang trang\n"Đặt lại mật khẩu"
        deactivate client
    end
end
@enduml
