@startuml Reset_Password_Sequence
skinparam sequenceArrowThickness 1.5
skinparam roundcorner 8
skinparam responseMessageBelowArrow true
skinparam sequenceGroupBorderThickness 1.5

skinparam participant {
    BackgroundColor #EEF4FF
    BorderColor #4A7CFF
    FontStyle Bold
}
skinparam actor {
    BackgroundColor #FEFEFE
    BorderColor #333333
}
skinparam sequence {
    LifeLineBorderColor  #888888
    GroupBorderColor     #888888
    GroupBodyBackgroundColor #FAFAFA
    DividerBackgroundColor   #E8E8E8
}
actor "Khách vãng lai" as User
participant "Client" as client
participant "AuthController" as controller
participant "AuthService" as service
participant "MailService" as mailService
participant "UserRepo" as repo
database "Redis" as redis
database "Database (MySQL)" as DB

User -> client : sendResetPasswordOTP(email)
activate client

client -> controller : sendResetPasswordOTP(email)
activate controller

controller   -> service : sendResetPasswordOTP(email)
activate service

service  -> repo  : findUserByEmail(email)
activate repo

repo  -> DB  : findUserByEmail(email)
activate DB

DB   --> repo : user
deactivate DB

repo   --> service : user
deactivate repo

alt user = null
    service  --> controller : userNotFoundError
    controller  --> client : apiResponse
    client --> User : Thông báo lỗi:\n"Email chưa được đăng ký\n hoặc sai định dạng"

else user != null
    service  -> service  : otp = generateOTP()
    activate service
    deactivate service

    service  -> redis   : saveOTP(otp)
    activate redis
    redis --> service : result
    deactivate redis

    service ->> mailService: sendOTPMail(mail, otp)
    activate mailService
    mailService -->> User: Gửi email chứa mã OTP
    deactivate mailService

    service  --> controller  : result
    deactivate service

    controller  --> client  : apiResponse
    deactivate controller

    client  --> User : Thông báo thành công,\nChuyển sang trang\n"Đặt lại mật khẩu"
    deactivate client
end

User -> client  : resetPassword(opt, newPassword, confirmPassword)
activate client
client -> controller  : resetPassword(opt, newPassword, confirmPassword)
activate controller

controller -> service : resetPassword(opt, newPassword, confirmPassword)
activate service

service -> service : result = validateResetPassword(opt, newPassword, confirmPassword)
activate service
deactivate service

alt result.success = false
    service --> controller: result

    controller --> client: apiResponse
    alt apiResponse.cause = "OTP"
        client --> User : Thông báo lỗi: "OTP sai hoặc hết hạn"
    else apiResponse.cause = "Password"
        client --> User : Thông báo lỗi: "Mật khẩu không hợp lệ"
    end
else apiResponse.success = true
    activate service
    service  -> service  : hashedPassword = hashPassword(newPassword)
    service  -> DB : updatePasswordByUserId(user.id, hashedPassword)

    activate DB
    DB   --> service : result
    deactivate DB

    service  -> redis : deleteOTP(otp)
    activate redis
    redis --> service : result
    deactivate redis

    service --> controller : result
    deactivate service

    controller --> client: apiResponse
    deactivate controller

    client --> User : Thông báo "Đổi mật khẩu thành công!",\n Chuyển hướng về trang Đăng nhập
    deactivate client
end
@enduml
