@startuml Reset_Password_Sequence
skinparam sequenceArrowThickness 1.5
skinparam roundcorner 8
skinparam responseMessageBelowArrow true
skinparam sequenceGroupBorderThickness 1.5

skinparam participant {
    BackgroundColor #EEF4FF
    BorderColor #4A7CFF
    FontStyle Bold
}
skinparam actor {
    BackgroundColor #FEFEFE
    BorderColor #333333
}
skinparam sequence {
    LifeLineBorderColor  #888888
    GroupBorderColor     #888888
    GroupBodyBackgroundColor #FAFAFA
    DividerBackgroundColor   #E8E8E8
}
actor "Khách vãng lai" as User
participant "Client" as client
participant "AuthController" as controller
participant "AuthService" as service
participant "EmailService" as mailService
participant "UserRepo" as repo
participant "RedisService" as redis
database "Database" as DB

User -> client  : resetPassword(request)
activate client
alt Mật khẩu sai định dạng
    client --> User : Thông báo lỗi:\n"Mật khẩu sai định dạng"
else Mật khẩu đúng định dạng
    client -> controller  : resetPassword(request)
    activate controller

    controller -> service : resetPassword(request)
    activate service

    alt Mật khẩu xác nhận và mật khẩu mới không khớp
        service --> controller: ConfirmPasswordNotMatchError
        controller --> client: responseEntity
        client --> User : Thông báo lỗi:\n"Mật khẩu xác nhận và\nmật khẩu mới không khớp"
    else Mật khẩu xác nhận khớp mật khẩu mới
        service -> redis : get(email))
        activate redis
        redis --> service : otp
        deactivate redis

        alt OTP sai hoặc hết hạn
            service --> controller: OTPInvalidError
            controller --> client: responseEntity
            client --> User : Thông báo lỗi:\n"OTP sai hoặc hết hạn"
        else OTP hợp lệ
            service  -> repo : save(user)
            activate repo

            repo -> DB: save(user)
            activate DB

            DB --> repo : result
            deactivate DB

            repo --> service: result
            deactivate repo

            service  -> redis : delete(email)
            activate redis
            redis --> service : result
            deactivate redis

            service --> controller : result
            deactivate service

            controller --> client: responseEntity
            deactivate controller

            client --> User : Thông báo "Đổi mật khẩu thành công!",\n Chuyển hướng về trang Đăng nhập
            deactivate client
        end
    end
end
@enduml