@startuml

skinparam sequenceArrowThickness 1.5
skinparam roundcorner 8
skinparam responseMessageBelowArrow true
skinparam sequenceGroupBorderThickness 1.5

skinparam participant {
    BackgroundColor #EEF4FF
    BorderColor     #4A7CFF
    FontStyle       Bold
}
skinparam actor {
    BackgroundColor #FEFEFE
    BorderColor     #333333
}
skinparam sequence {
    LifeLineBorderColor  #888888
    GroupBorderColor     #888888
    GroupBodyBackgroundColor #FAFAFA
    DividerBackgroundColor   #E8E8E8
}

actor "Người dùng" as User
participant "Client" as client
participant "UserController" as controller
participant "UserService" as service
participant "EmailService" as mailService
database "RedisService" as redis

User -> client : sendOTPUpdateEmail(request)
activate client

alt Email không đúng định dạng
    client --> User : Thông báo lỗi:\n"Email không đúng định dạng"
else Email đúng định dạng
    client -> controller : sendOTPUpdateEmail(request)
    activate controller

    controller -> service : sendOTPUpdateEmail(username, request)
    activate service

    alt Email mới trùng email cũ
        service --> controller : EmailUnchangedError
        controller --> client : responseEntity
        client --> User : Thông báo lỗi:\n"Email mới trùng email cũ"
    else Email đã tồn tại
        service --> controller : EmailExistedError
        controller --> client : responseEntity
        client --> User : Thông báo lỗi:\n"Email đã tồn tại"
    else Email chưa tồn tại
        service -> service : oldEmailOtp = generateOTP()
        activate service
        deactivate service

        service -> service : newEmailOtp = generateOTP()
        activate service
        deactivate service

        service -> redis : save(oldEmailOtpKey, oldEmailOtp, timeoutInMinutes)
        activate redis
        redis --> service : result
        deactivate redis

        service -> redis : save(newEmailOtpKey, newEmailOtp, timeoutInMinutes)
        activate redis
        redis --> service : result
        deactivate redis

        service ->> mailService : sendEmail(oldEmail, username,\notpTemplate, oldEmailOtp, subject)
        activate mailService
        mailService -->> User : Gửi OTP đên email cũ

        service ->> mailService : sendEmail(newEmail, username,\notpTemplate, newEmailOtp, subject)
        mailService -->> User : Gửi OTP đên email mới
        deactivate mailService

        service --> controller : result
        deactivate service
        controller --> client : responseEntity
        deactivate controller

        client --> User : Mở form nhập mã OTP
        deactivate client
    end
end
@enduml