app:
  front-end-domain: "https://production-domain.com"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elingo
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    com.elingo: INFO
  file:
    name: logs/elingo.log