app:
  front-end-domain: "http://localhost:5173"
  google:
    client-id: ${DEV_GOOGLE_CLIENT_ID}

spring:
  datasource:
    url: ${DEV_MYSQL_CONNECTION_URL:jdbc:mysql://localhost:3306/elingo}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${DEV_MAIL_HOST}
    port: ${DEV_MAIL_PORT}
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}

jwt:
  signer-key: ${DEV_JWT_SIGNER_KEY}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    com.elingo: DEBUG
    org.hibernate.SQL: DEBUG