server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: elingo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  accessTokenTime: 15 # minute
  refreshTokenTime: 14 # day

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha